# Generated by Django 4.1.2 on 2023-02-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_testimony_created_at_testimony_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_poster_image',
            field=models.FileField(default=models.CharField(max_length=200, unique=True), upload_to='videos_poster_image'),
        ),
    ]
