# Generated by Django 4.1.2 on 2023-02-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_videos_video_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_poster_image',
            field=models.ImageField(default=models.CharField(max_length=200, unique=True), upload_to='videos_poster_image'),
        ),
    ]
