# Generated by Django 4.1.7 on 2023-02-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_alter_videos_video_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_setting',
            name='company_logo',
            field=models.ImageField(blank=True, default='companylogo', null=True, upload_to='logo'),
        ),
    ]
