# Generated by Django 4.1.7 on 2023-03-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_website_setting_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signals',
            name='features',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
